### PR TITLE
add support for async in data-attr.js

### PR DESCRIPTION
**Pull request by matteo-hertel**
As mentioned in #5 when the async attribute is used the DOM is already loaded so I've added an extra bit of logic to check if the document is loaded, if it is, then init the data-attr.js otherwise wait for the dome to be ready and then init it.

I've also added the async-test.js to replicate the demo in the issue and check that everything is working fine.

there are a couple more places where this async problem might need to be fixed, if my solution is accepted I'll go ahead and fix the rest of it

### CODE REVIEW

**Comment by jakeburden** [comment]
Greetings @matteo-hertel 👋  👋 

Sweet! 🎉  I really like how you've included a new test.

If you'd be willing to repeat this solution where needed (anywhere that listens for DOMContentLoaded) I'd be super grateful. Looks like you have a really good grasp on this repo but don't be shy if you run into any question. 

Thank you so much for submitting this pull request! 🌴

**Comment by matteo-hertel** [comment]
Hello @jekrb!

I'll gladly add the same logic where is needed!

**Comment by matteo-hertel** [comment]
this should be done now!

**Comment by jakeburden** [comment]
merged and published to npm

😃  thank you so much for the contribution!

**Comment by matteo-hertel** [comment]
Thank you for merging!

**Pull request merged**
